prepend-code: |-
  $env.config.footer_mode = 'always';
  $env.config.table = {mode: rounded, index_mode: never,
  show_empty: false, padding: {left: 1, right: 1},
  trim: {methodology: truncating, wrapping_try_keep_words: false, truncating_suffix: ...},
  header_on_separator: true, abbreviated_row_count: 1000}
